# Generated by Django 5.0.3 on 2024-07-28 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_auth", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Profile",
        ),
    ]
