# Generated by Django 5.0.3 on 2024-05-27 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FaceEncoding',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
