'use client';
import '../styles/global.css';
import { Inter } from 'next/font/google';
import { useEffect } from 'react';
import { refreshToken } from './utils/auth';
const inter = Inter({ subsets: ['latin'] });

// export const metadata = {
//   title: 'Next.js App',
//   description: 'Generated by create next app',
// };


export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  useEffect(() => {
    refreshToken(); // Refresh the token immediately on load

    const interval = setInterval(refreshToken, 840000); //set to 14 minutes
    

    return () => clearInterval(interval);
  }, []);

  
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
