# Generated by Django 5.0.3 on 2024-05-27 22:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_alter_attendance_course_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaceEncoding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encoding', models.TextField()),
                ('student_exam_number', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='attendance.student')),
            ],
            options={
                'db_table': 'face_encoding',
            },
        ),
    ]
