# Generated by Django 5.0.3 on 2024-05-27 22:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_faceencoding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faceencoding',
            name='student_exam_number',
            field=models.OneToOneField(db_column='student_exam_number', on_delete=django.db.models.deletion.CASCADE, to='attendance.student'),
        ),
    ]
